CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "Categorias" (
    "CategoriaId" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nombre" text NOT NULL,
    "Descripcion" text NOT NULL,
    CONSTRAINT "PK_Categorias" PRIMARY KEY ("CategoriaId")
);

CREATE TABLE "Organizaciones" (
    "OrganizacionId" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nombre" text NOT NULL,
    "Descripcion" text NOT NULL,
    "DominioEmail" text NOT NULL,
    "Activa" boolean NOT NULL,
    CONSTRAINT "PK_Organizaciones" PRIMARY KEY ("OrganizacionId")
);

CREATE TABLE "Reconocimientos" (
    "ReconocimientoId" integer GENERATED BY DEFAULT AS IDENTITY,
    "TokenColaborador" text NOT NULL,
    "Justificacion" text NOT NULL,
    "Texto" text NOT NULL,
    "Titulo" text NOT NULL,
    "FechaCreacion" text NOT NULL,
    "Estado" text NOT NULL,
    "ComentarioRevision" text NOT NULL,
    "FechaResolucion" text NOT NULL,
    CONSTRAINT "PK_Reconocimientos" PRIMARY KEY ("ReconocimientoId")
);

CREATE TABLE "WalletCategorias" (
    "CategoriaId" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nombre" text NOT NULL,
    "Descripcion" text NOT NULL,
    CONSTRAINT "PK_WalletCategorias" PRIMARY KEY ("CategoriaId")
);

CREATE TABLE "WalletSaldos" (
    "WalletSaldoId" integer GENERATED BY DEFAULT AS IDENTITY,
    "TokenColaborador" text NOT NULL,
    "SaldoActual" integer NOT NULL,
    CONSTRAINT "PK_WalletSaldos" PRIMARY KEY ("WalletSaldoId")
);

CREATE TABLE "Colaboradores" (
    "ColaboradorId" text NOT NULL,
    "OrganizacionId" integer NOT NULL,
    "ExcepcionConfiguracion" boolean NOT NULL,
    CONSTRAINT "PK_Colaboradores" PRIMARY KEY ("ColaboradorId"),
    CONSTRAINT "FK_Colaboradores_Organizaciones_OrganizacionId" FOREIGN KEY ("OrganizacionId") REFERENCES "Organizaciones" ("OrganizacionId") ON DELETE CASCADE
);

CREATE TABLE "Comportamientos" (
    "ComportamientoId" integer GENERATED BY DEFAULT AS IDENTITY,
    "OrganizacionId" integer NOT NULL,
    "Nombre" text NOT NULL,
    "Descripcion" text NOT NULL,
    "WalletOtorgados" integer NOT NULL,
    CONSTRAINT "PK_Comportamientos" PRIMARY KEY ("ComportamientoId"),
    CONSTRAINT "FK_Comportamientos_Organizaciones_OrganizacionId" FOREIGN KEY ("OrganizacionId") REFERENCES "Organizaciones" ("OrganizacionId") ON DELETE CASCADE
);

CREATE TABLE "MarketplacePremios" (
    "PremioId" integer GENERATED BY DEFAULT AS IDENTITY,
    "OrganizacionId" integer NOT NULL,
    "CategoriaId" integer NOT NULL,
    "Nombre" text NOT NULL,
    "Descripcion" text NOT NULL,
    "CostoWallet" integer NOT NULL,
    "ImagenUrl" text NOT NULL,
    "CantidadActual" integer NOT NULL,
    "UltimaActualizacion" text NOT NULL,
    CONSTRAINT "PK_MarketplacePremios" PRIMARY KEY ("PremioId"),
    CONSTRAINT "FK_MarketplacePremios_Categorias_CategoriaId" FOREIGN KEY ("CategoriaId") REFERENCES "Categorias" ("CategoriaId") ON DELETE CASCADE,
    CONSTRAINT "FK_MarketplacePremios_Organizaciones_OrganizacionId" FOREIGN KEY ("OrganizacionId") REFERENCES "Organizaciones" ("OrganizacionId") ON DELETE CASCADE
);

CREATE TABLE "WalletTransacciones" (
    "TransaccionId" integer GENERATED BY DEFAULT AS IDENTITY,
    "WalletSaldoId" integer NOT NULL,
    "TokenColaborador" text NOT NULL,
    "CategoriaId" integer NOT NULL,
    "Cantidad" integer NOT NULL,
    "Descripcion" text NOT NULL,
    "Fecha" text NOT NULL,
    CONSTRAINT "PK_WalletTransacciones" PRIMARY KEY ("TransaccionId"),
    CONSTRAINT "FK_WalletTransacciones_WalletCategorias_CategoriaId" FOREIGN KEY ("CategoriaId") REFERENCES "WalletCategorias" ("CategoriaId") ON DELETE CASCADE,
    CONSTRAINT "FK_WalletTransacciones_WalletSaldos_WalletSaldoId" FOREIGN KEY ("WalletSaldoId") REFERENCES "WalletSaldos" ("WalletSaldoId") ON DELETE CASCADE
);

CREATE TABLE "ReconocimientoComportamientos" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ReconocimientoId" integer NOT NULL,
    "ComportamientoId" integer NOT NULL,
    CONSTRAINT "PK_ReconocimientoComportamientos" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ReconocimientoComportamientos_Comportamientos_Comportamient~" FOREIGN KEY ("ComportamientoId") REFERENCES "Comportamientos" ("ComportamientoId") ON DELETE CASCADE,
    CONSTRAINT "FK_ReconocimientoComportamientos_Reconocimientos_Reconocimient~" FOREIGN KEY ("ReconocimientoId") REFERENCES "Reconocimientos" ("ReconocimientoId") ON DELETE CASCADE
);

CREATE TABLE "InventarioTransacciones" (
    "TransaccionId" integer GENERATED BY DEFAULT AS IDENTITY,
    "PremioId" integer NOT NULL,
    "TipoMovimiento" text NOT NULL,
    "Cantidad" integer NOT NULL,
    "Descripcion" text NOT NULL,
    "Fecha" text NOT NULL,
    CONSTRAINT "PK_InventarioTransacciones" PRIMARY KEY ("TransaccionId"),
    CONSTRAINT "FK_InventarioTransacciones_MarketplacePremios_PremioId" FOREIGN KEY ("PremioId") REFERENCES "MarketplacePremios" ("PremioId") ON DELETE CASCADE
);

CREATE TABLE "MarketplaceCompras" (
    "CompraId" integer GENERATED BY DEFAULT AS IDENTITY,
    "TokenColaborador" text NOT NULL,
    "PremioId" integer NOT NULL,
    "FechaCompra" text NOT NULL,
    "Estado" text NOT NULL,
    "ComentarioRevision" text NOT NULL,
    "FechaResolucion" text NOT NULL,
    CONSTRAINT "PK_MarketplaceCompras" PRIMARY KEY ("CompraId"),
    CONSTRAINT "FK_MarketplaceCompras_MarketplacePremios_PremioId" FOREIGN KEY ("PremioId") REFERENCES "MarketplacePremios" ("PremioId") ON DELETE CASCADE
);

CREATE INDEX "IX_Colaboradores_OrganizacionId" ON "Colaboradores" ("OrganizacionId");

CREATE INDEX "IX_Comportamientos_OrganizacionId" ON "Comportamientos" ("OrganizacionId");

CREATE INDEX "IX_InventarioTransacciones_PremioId" ON "InventarioTransacciones" ("PremioId");

CREATE INDEX "IX_MarketplaceCompras_PremioId" ON "MarketplaceCompras" ("PremioId");

CREATE INDEX "IX_MarketplacePremios_CategoriaId" ON "MarketplacePremios" ("CategoriaId");

CREATE INDEX "IX_MarketplacePremios_OrganizacionId" ON "MarketplacePremios" ("OrganizacionId");

CREATE INDEX "IX_ReconocimientoComportamientos_ComportamientoId" ON "ReconocimientoComportamientos" ("ComportamientoId");

CREATE INDEX "IX_ReconocimientoComportamientos_ReconocimientoId" ON "ReconocimientoComportamientos" ("ReconocimientoId");

CREATE INDEX "IX_WalletTransacciones_CategoriaId" ON "WalletTransacciones" ("CategoriaId");

CREATE INDEX "IX_WalletTransacciones_WalletSaldoId" ON "WalletTransacciones" ("WalletSaldoId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250507152940_InitialMigration', '9.0.4');

COMMIT;

