services:
  spa:
    image: ghcr.io/nfcvec/reconoser-spa:latest
    build:
      context: ./ReconocerApp.SPA
      dockerfile: Dockerfile
      args:
        - SKIP_PREFLIGHT_CHECK=SKIP_PREFLIGHT_CHECK=true
        - BROWSER=BROWSER=none
        # - VITE_CLIENT_ID=6885bc59-dbd5-4d8b-a3b2-b753ca53d2c4
        # - VITE_AUTHORITY=https://login.microsoftonline.com/abcce23f-bc94-47e2-834f-01fd1e3d7f7b
        - VITE_CLIENT_ID=3c1288d3-314b-4ab3-9669-11ab1909e1ab
        - VITE_AUTHORITY=https://login.microsoftonline.com/05b4b405-3325-479b-88fd-f6c25ea40a8c
        - VITE_POPUP_REDIRECT_URI=/redirect
        - VITE_TITLE=ReconoSER
        - VITE_API_URL=https://reconoser-api.lerolero.com.ec/api

  api:
    image: ghcr.io/nfcvec/reconoser-api:latest
    build:
      context: ./ReconocerApp.API
      dockerfile: Dockerfile
    environment:
      ConnectionStrings__DefaultConnection: "Host=192.168.10.40;Port=5432;Username=postgres;Password=Artes@nas240;Database=reconoser"
      DatabaseProvider: "PostgreSQL"
      Minio__Endpoint: "minio:9000"
      Minio__AccessKey: "minioadmin" # Usuario de acceso
      Minio__SecretKey: "Artes@nas240" # Contraseña de acceso
      Minio__BucketName: "reconoser" # Nombre del bucket
      Email__SmtpServer: "mail.upsecuador.com"
      Email__Port: "465"
      Email__Username: "notificaciones@upsecuador.com"
      Email__Password: "ekinotificaciones"
      Email__EnableSsl: "true"
      Email__FromAddress: "notificaciones@upsecuador.com"
      AzureAd__ClientId: "2462d3ca-37eb-4778-98e6-a322b99f5cce"
      AzureAd__TenantId: "2af6ae87-3287-4e29-a50a-680f5d852aa3"
      AzureAd__ClientSecret: "osD8Q~9c-aoRpC.5PMy_u5vdYYhii6p00jVaIcyw"
      FrontendUrl: "https://reconoser.lerolero.com.ec"
    depends_on:
      - minio

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000" # Puerto para el servicio de MinIO
      - "9001:9001" # Puerto para la consola de MinIO
    environment:
      MINIO_ROOT_USER: minioadmin # Usuario de acceso
      MINIO_ROOT_PASSWORD: minioadmin # Contraseña de acceso
    volumes:
      - minio_data:/data # Volumen para persistir datos
    command: server /data --console-address ":9001"
    restart: always

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token eyJhIjoiY2VjODk5MGQ1YWM2ODk5NzlkOWU1ZGE2MWZkNzQ4YzEiLCJ0IjoiODg1NmU2NWYtYWUxOC00NDZmLWI5ZTItY2UzOWVhN2E0ODI2IiwicyI6Ik1tVmxNR05sTTJVdE1XWmhZUzAwTXpCbUxXRTRaVGt0TmpVNU5HUmlOemRoWVRkbCJ9
    restart: unless-stopped

volumes:
  minio_data: