services:
  spa:
    image: ghcr.io/nfcvec/reconoser-spa:latest
    build:
      context: ./ReconocerApp.SPA
      dockerfile: Dockerfile
    networks:
      - reconoser-network

  api:
    image: ghcr.io/nfcvec/reconoser-api:latest
    build:
      context: ./ReconocerApp.API
      dockerfile: Dockerfile
    networks:
      - reconoser-network
    environment:
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Username=postgres;Password=postgres;Database=reconoser"
      DatabaseProvider: "PostgreSQL"
      Minio__Endpoint: "minio:9000"
      Minio__AccessKey: "minioadmin" # Usuario de acceso
      Minio__SecretKey: "minioadmin" # Contraseña de acceso
      Minio__BucketName: "reconoser" # Nombre del bucket
    depends_on:
      - db
      - minio

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: reconoser
    volumes:
      - ./db_data:/var/lib/postgresql/data
    networks:
      - reconoser-network

  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: minioadmin # Usuario de acceso
      MINIO_ROOT_PASSWORD: minioadmin # Contraseña de acceso
    volumes:
      - ./minio_data:/data # Volumen para persistir datos
    command: server /data --console-address ":9001"
    networks:
      - reconoser-network
    restart: always
networks:
  reconoser-network:
    external: true