services:
  spa:
    image: ghcr.io/nfcvec/reconoser-spa:latest
    build:
      context: ./ReconocerApp.SPA
      dockerfile: Dockerfile
      args:
        - SKIP_PREFLIGHT_CHECK=SKIP_PREFLIGHT_CHECK=true
        - BROWSER=BROWSER=none
        - VITE_CLIENT_ID=2462d3ca-37eb-4778-98e6-a322b99f5cce
        - VITE_AUTHORITY=https://login.microsoftonline.com/2af6ae87-3287-4e29-a50a-680f5d852aa3
        - VITE_POPUP_REDIRECT_URI=/redirect
        - VITE_TITLE=ReconoSER
        - VITE_API_URL=https://reconoser-api.lerolero.com.ec/api
    networks:
      - reconoser-network

  api:
    image: ghcr.io/nfcvec/reconoser-api:latest
    build:
      context: ./ReconocerApp.API
      dockerfile: Dockerfile
    networks:
      - reconoser-network
    environment:
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Username=postgres;Password=postgres;Database=reconoser"
      DatabaseProvider: "PostgreSQL"
      Minio__Endpoint: "minio:9000"
      Minio__AccessKey: "minioadmin" # Usuario de acceso
      Minio__SecretKey: "minioadmin" # Contraseña de acceso
      Minio__BucketName: "reconoser" # Nombre del bucket
    depends_on:
      - db
      - minio

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: reconoser
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - reconoser-network

  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: minioadmin # Usuario de acceso
      MINIO_ROOT_PASSWORD: minioadmin # Contraseña de acceso
    volumes:
      - minio_data:/data # Volumen para persistir datos
    command: server /data --console-address ":9001"
    networks:
      - reconoser-network
    restart: always
networks:
  reconoser-network:
    external: true

volumes:
  postgres_data:
  minio_data: