version: '3.8'

services:
  api:
    container_name: reconoser_api
    image: ghcr.io/nfcvec/reconoser-api:latest
    build:
      context: ./ReconocerApp.API
      dockerfile: Dockerfile
    environment:
      ConnectionStrings__DefaultConnection: "Host=192.168.10.40;Port=5432;Username=postgres;Password=Artes@nas240;Database=reconoser"
      DatabaseProvider: "PostgreSQL"
      Minio__Endpoint: "192.168.10.56:9000"
      Minio__AccessKey: "minioadmin"
      Minio__SecretKey: "Artes@nas240"
      Minio__BucketName: "reconoser"
      Email__SmtpServer: "mail.upsecuador.com"
      Email__Port: "465"
      Email__Username: "notificaciones@upsecuador.com"
      Email__Password: "ekinotificaciones"
      Email__EnableSsl: "true"
      Email__FromAddress: "notificaciones@upsecuador.com"
      GraphEmail__ClientId: "9b9b617d-16a4-4371-b015-1433fb9c1251"
      GraphEmail__TenantId: "abcce23f-bc94-47e2-834f-01fd1e3d7f7b"
      GraphEmail__ClientSecret: "6ee8Q~IjuqOsk0nFrSI5DCUhfq6nGJn4XGwm1awT"
      GraphEmail__UserId: "preparat@academikus.com"
      AzureAd__ClientId: "3c1288d3-314b-4ab3-9669-11ab1909e1ab"
      AzureAd__TenantId: "05b4b405-3325-479b-88fd-f6c25ea40a8c"
      AzureAd__ClientSecret: "4dQ8Q~i-K~.biFHAyxERbzj3_G7f62K7KdbDfduR"
      FrontendUrl: "https://reconoser.lerolero.com.ec"
    restart: always

  spa:
    container_name: reconoser_spa
    image: ghcr.io/nfcvec/reconoser-spa:latest
    build:
      context: ./ReconocerApp.SPA
      dockerfile: Dockerfile
      args:
        - SKIP_PREFLIGHT_CHECK=SKIP_PREFLIGHT_CHECK=true
        - BROWSER=BROWSER=none
        - VITE_CLIENT_ID=3c1288d3-314b-4ab3-9669-11ab1909e1ab
        - VITE_AUTHORITY=https://login.microsoftonline.com/05b4b405-3325-479b-88fd-f6c25ea40a8c
        - VITE_POPUP_REDIRECT_URI=/redirect
        - VITE_TITLE=ReconoSER
        - VITE_API_URL=https://reconoser-api.lerolero.com.ec/api
    environment:
      - NODE_ENV=production
    restart: always

  nginx:
    image: nginx:latest
    container_name: reconoser_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - spa
      - api
    restart: always

volumes:
  minio_data: