name: Docker Image CI

on:
  push:
    branches: [ "Dev" ]
  pull_request:
    branches: [ "Dev" ]

jobs:

  build:

    runs-on: Dev

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker Compose
      run: docker compose build
    - uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Push the Docker Compose
      run: docker compose push
    - name: Get the Docker Compose
      run: docker compose pull
    - name: Stop the Docker Compose
      run: docker compose down
    - name: Start the Docker Compose
      run: docker compose up -d
