name: Docker Image CI

on:
  push:
    branches: [ "Dev" ]
  pull_request:
    branches: [ "Dev" ]

jobs:

  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker Compose
      run: docker compose build
    - uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Push the Docker Compose
      run: docker compose push

  deploy:
    runs-on: Dev
    needs: build-and-push
    steps:
    - uses: actions/checkout@v4
    - uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Get the Docker Compose
      run: docker compose pull
    - name: Stop the Docker Compose
      run: docker compose down
    - name: Start the Docker Compose
      run: docker compose up -d
